server:
  strategy: Mean # Options: [Mean, Median, Trimmed Mean, Bulyan, Multi-Krum, Krum, FedGreed, Loss-Based Clustering]
  fraction_fit: 1.0
  fraction_eval: 1.0
  dataset_size: 1.0
  num_rounds: 5
  batch_size: 64
client:
  num_clients: 10
  batch_size: 64
  local_epochs: 5
model:
  name: MNIST
  learning_rate: 0.001
attack:
  activation_round: 1
  num_malicious_clients: 5
  type: Sign Flip # Options: [Sign Flip, Label Flip, Gaussian Noise]
  mean: 0.0 # Only applicable for Gaussian Noise attack
  std: 1.0 # Only applicable for Gaussian Noise attack
defence:
  activation_round: 1
general:
  use_wandb: false
  random_seed: 42
backend:
  client_resources:
    num_cpus: 2.0
    num_gpus: 0.0

use_case:
  name: "AVISENCE"
  data_split: "iid" # non-iid or iid
  data_config_path: "config/labels/semantic-poss.yaml"
  model_architecture_config_path: "config/arch/LENet_poss.yaml"
  data_dir: "./avisence_datasets/poss/dataset/SemanticPOSS"
